[functions.create-checkout-session]
verify_jwt = true

[functions.create-portal-session]
verify_jwt = true

[functions.cancel-subscription]
verify_jwt = true

[functions.reactivate-subscription]
verify_jwt = true

[functions.webhook-handler]
verify_jwt = false 