version: '3.8'

services:
  app:
    image:  ghcr.io/ireccode/sap-exam-prep:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 1h
        max_attempts: 3
      update_config:
        parallelism: 1
        order: start-first
        failure_action: pause
    ports:
      - target: 5173
        published: 5173
        protocol: tcp
        mode: host
    secrets:
      - source: VITE_SUPABASE_URL
        target: VITE_SUPABASE_URL
      - source: VITE_SUPABASE_ANON_KEY
        target: VITE_SUPABASE_ANON_KEY
      - source: VITE_STRIPE_PUBLISHABLE_KEY
        target: VITE_STRIPE_PUBLISHABLE_KEY
      - source: VITE_STRIPE_PREMIUM_PRICE_ID
        target: VITE_STRIPE_PREMIUM_PRICE_ID
      - source: VITE_BASIC_ENCRYPTION_KEY
        target: VITE_BASIC_ENCRYPTION_KEY
      - source: VITE_PREMIUM_ENCRYPTION_KEY
        target: VITE_PREMIUM_ENCRYPTION_KEY
      - source: VITE_WEBHOOK_SECRET
        target: VITE_WEBHOOK_SECRET
      - source: VITE_OPENROUTER_API_KEY
        target: VITE_OPENROUTER_API_KEY
    environment:
      - NODE_ENV=production
      - VIRTUAL_PROTO=https
      - VITE_SUPABASE_URL_FILE=/run/secrets/VITE_SUPABASE_URL
      - VITE_SUPABASE_ANON_KEY_FILE=/run/secrets/VITE_SUPABASE_ANON_KEY
      - VITE_STRIPE_PUBLISHABLE_KEY_FILE=/run/secrets/VITE_STRIPE_PUBLISHABLE_KEY
      - VITE_STRIPE_PREMIUM_PRICE_ID_FILE=/run/secrets/VITE_STRIPE_PREMIUM_PRICE_ID
      - VITE_BASIC_ENCRYPTION_KEY_FILE=/run/secrets/VITE_BASIC_ENCRYPTION_KEY
      - VITE_PREMIUM_ENCRYPTION_KEY_FILE=/run/secrets/VITE_PREMIUM_ENCRYPTION_KEY
      - VITE_WEBHOOK_SECRET_FILE=/run/secrets/VITE_WEBHOOK_SECRET
      - VITE_OPENROUTER_API_KEY_FILE=/run/secrets/VITE_OPENROUTER_API_KEY
    volumes:
      - logs:/var/log/nginx
      - data:/app/data
      - public:/app/public
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    user: root
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./examprep_app_nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
      - type: bind
        source: ./init-certs.sh
        target: /docker-entrypoint.d/init-certs.sh
    environment:
      - NGINX_HOST=examprep.techtreasuretrove.in
      - NGINX_PORT=443
      - NGINX_CERT_EMAIL=narkanie00@gmail.com
    command: |
      /bin/sh -c "
      apk add --no-cache openssl curl bind-tools certbot certbot-nginx &&
      chmod +x /docker-entrypoint.d/init-certs.sh &&
      /docker-entrypoint.d/init-certs.sh &&
      nginx -g 'daemon off;'"
    depends_on:
      - app
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 1h
        max_attempts: 3

networks:
  app-network:
    driver: overlay

volumes:
  logs:
  data:
  public:

secrets:
  VITE_SUPABASE_URL:
    external: true
  VITE_SUPABASE_ANON_KEY:
    external: true
  VITE_STRIPE_PUBLISHABLE_KEY:
    external: true
  VITE_STRIPE_PREMIUM_PRICE_ID:
    external: true
  VITE_BASIC_ENCRYPTION_KEY:
    external: true
  VITE_PREMIUM_ENCRYPTION_KEY:
    external: true
  VITE_WEBHOOK_SECRET:
    external: true
  VITE_OPENROUTER_API_KEY:
    external: true
