version: '3.8'

services:
  app:
    build:
      context: .
      target: app
    image: ghcr.io/ireccode/sap-exam-prep:${GIT_COMMIT_HASH:-latest}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "5173:5173"
    expose:
      - 5173
    env_file: ./.env
    environment:
      - NODE_ENV=development
      - VIRTUAL_PROTO=https
    volumes:
      - logs:/var/log/nginx
      - data:/app/data
      - public:/app/public
      - /etc/letsencrypt:/etc/letsencrypt
      - dist:/app/dist
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5173/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  nginx:
    build:
      context: . 
      target: nginx      
    image: ghcr.io/ireccode/sap-exam-prep-nginx:${GIT_COMMIT_HASH:-latest}
    user: root
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./examprep_app_nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
      - type: bind
        source: ./init-certs.sh
        target: /docker-entrypoint.d/init-certs.sh
    environment:
      - NGINX_HOST=examprep.techtreasuretrove.in
      - NGINX_PORT=443
      - NGINX_CERT_EMAIL=narkanie00@gmail.com
    command: |
      /bin/sh -c "
      apk add --no-cache openssl curl bind-tools certbot certbot-nginx &&
      chmod +x /docker-entrypoint.d/init-certs.sh &&
      /docker-entrypoint.d/init-certs.sh &&
      nginx -g 'daemon off;'"
    depends_on:
      app:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    attachable: true

volumes:
  logs:
  data:
  public:
  dist:
