version: '3.8'

services:
  app:
    image: ghcr.io/ireccode/sap-exam-prep:latest
    deploy:
      replicas: 1
    update_config:
      parallelism: 1
      order: start-first
      failure_action: pause
      delay: 10s
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
    resources:
      limits:
        cpus: '0.5'
        memory: 512M
      reservations:
        cpus: '0.1'
        memory: 128M
    ports:
      - target: 5173
        published: 5173
        protocol: tcp
        mode: host
    environment:
      - NODE_ENV=production
      - VIRTUAL_PROTO=https
    volumes:
      - logs:/var/log/nginx
      - data:/app/data
      - public:/app/public
      - /etc/letsencrypt:/etc/letsencrypt
      - dist:/app/dist
      # Mount the .env file from the host to the container
      - type: bind
        source: ./.env.production
        target: /app/.env
        read_only: true
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5173/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  nginx:
    image: ghcr.io/ireccode/sap-exam-prep-nginx:latest
    user: root
    deploy:
      replicas: 2
    update_config:
      parallelism: 1
      order: start-first
      failure_action: pause
      delay: 10s
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
    resources:
      limits:
        cpus: '0.3'
        memory: 256M
      reservations:
        cpus: '0.05'
        memory: 64M
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./examprep_app_nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
      - type: bind
        source: ./init-certs.sh
        target: /docker-entrypoint.d/init-certs.sh
      - dist:/usr/share/nginx/html:ro
    environment:
      - NGINX_HOST=saparchitectprep.com
      - NGINX_PORT=443
      - NGINX_CERT_EMAIL=support@saparchitectprep.com
    command: |
      /bin/sh -c "
      apk add --no-cache openssl curl bind-tools certbot certbot-nginx &&
      chmod +x /docker-entrypoint.d/init-certs.sh &&
      /docker-entrypoint.d/init-certs.sh &&
      nginx -g 'daemon off;'"
    depends_on:
      - app
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s

networks:
  app-network:
    driver: overlay
    driver_opts:
      encrypted: "true"

volumes:
  logs:
    driver: local
  data:
    driver: local
  public:
    driver: local
  dist:
    driver: local
