version: '3.8'

services:
  app:
    build:
      context: .
      target: app
    image: ghcr.io/ireccode/sap-exam-prep:${GIT_COMMIT_HASH:-latest}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "5173:5173"
    expose:
      - 5173
    env_file: ./.env
    environment:
      - PORT=5173
      - NODE_ENV=production
    volumes:
      - logs:/var/log/nginx
      - data:/app/data
      - public:/app/public
      - /etc/letsencrypt:/etc/letsencrypt
      - dist:/app/dist
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5173/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  nginx:
    build:
      context: .
    image: ghcr.io/ireccode/sap-exam-prep:${GIT_COMMIT_HASH:-latest}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL:-https://cwscaerzmixftirytvwo.supabase.co}
    volumes:
      - ./logs:/var/log/nginx
      - ./data:/app/data
      - ./public:/app/public
      - ./dist:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
      - ./.env.production:/usr/share/nginx/html/.env:ro
      - ./.env:/.env:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    attachable: true

volumes:
  logs:
  data:
  public:
  dist:
