version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
        - VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY}
        - VITE_STRIPE_PREMIUM_PRICE_ID=${VITE_STRIPE_PREMIUM_PRICE_ID}
        - VITE_BASIC_ENCRYPTION_KEY=${VITE_BASIC_ENCRYPTION_KEY}
        - VITE_PREMIUM_ENCRYPTION_KEY=${VITE_PREMIUM_ENCRYPTION_KEY}
        - VITE_WEBHOOK_SECRET=${VITE_WEBHOOK_SECRET}
        - VITE_OPENROUTER_API_KEY=${VITE_OPENROUTER_API_KEY}
    container_name: sap-exam-prep-app
    image: ghcr.io/ireccode/sap-exam-prep:${GIT_COMMIT_HASH:-latest}
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=examprep.techtreasuretrove.in
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=examprep.techtreasuretrove.in
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY}
      - VITE_STRIPE_PREMIUM_PRICE_ID=${VITE_STRIPE_PREMIUM_PRICE_ID}
      - VITE_BASIC_ENCRYPTION_KEY=${VITE_BASIC_ENCRYPTION_KEY}
      - VITE_PREMIUM_ENCRYPTION_KEY=${VITE_PREMIUM_ENCRYPTION_KEY}
      - VITE_WEBHOOK_SECRET=${VITE_WEBHOOK_SECRET}
      - VITE_OPENROUTER_API_KEY=${VITE_OPENROUTER_API_KEY}
    restart: unless-stopped
    volumes:
      - ./logs:/var/log/nginx
      - ./data:/app/data
      - ./dist:/app/public
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  logs:
  data: 
  public:
  letsencrypt:
  nginx:
