version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
        - VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY}
        - VITE_STRIPE_PREMIUM_PRICE_ID=${VITE_STRIPE_PREMIUM_PRICE_ID}
        - VITE_OPENROUTER_API_KEY=${VITE_OPENROUTER_API_KEY}
        - VITE_PREMIUM_ENCRYPTION_KEY=${VITE_PREMIUM_ENCRYPTION_KEY}
        - VITE_WEBHOOK_SECRET=${VITE_WEBHOOK_SECRET}
    container_name: sap-exam-prep-app
    ports:
      - "5175:5173"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./logs:/var/log/nginx
      - ./data:/app/data

networks:
  app-network:
    driver: bridge

volumes:
  logs:
  data: 