name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  APP_IMAGE_NAME: ireccode/sap-exam-prep
  NGINX_IMAGE_NAME: ireccode/sap-exam-prep-nginx

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      # Create environment file for build
      - name: Create environment file
        run: |
          cat > .env.production << EOF
          # Supabase Configuration (client-side)
          VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}
          
          # Stripe Configuration (client-side)
          VITE_STRIPE_PUBLISHABLE_KEY=${{ secrets.VITE_STRIPE_PUBLISHABLE_KEY }}
          VITE_STRIPE_PREMIUM_PRICE_ID=${{ secrets.VITE_STRIPE_PREMIUM_PRICE_ID }}
          
          # Encryption Keys (server-side only)
          BASIC_ENCRYPTION_KEY=${{ secrets.BASIC_ENCRYPTION_KEY }}
          PREMIUM_ENCRYPTION_KEY=${{ secrets.PREMIUM_ENCRYPTION_KEY }}
          
          # API Keys (server-side only)
          OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}
          WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET }}
          
          # Build Information
          GIT_COMMIT_HASH=${{ github.sha }}
          EOF

      # Extract metadata for app image
      - name: Extract metadata for app image
        id: meta-app
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.APP_IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=raw,value=${{ github.sha }}
            type=raw,value=latest,enable={{is_default_branch}}

      # Extract metadata for nginx image
      - name: Extract metadata for nginx image
        id: meta-nginx
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.NGINX_IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=raw,value=${{ github.sha }}
            type=raw,value=latest,enable={{is_default_branch}}

      # Build and push app image
      - name: Build and push app Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: app
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-app.outputs.tags }}
          labels: ${{ steps.meta-app.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GIT_COMMIT_HASH=${{ github.sha }}
            BASIC_ENCRYPTION_KEY=${{ secrets.BASIC_ENCRYPTION_KEY }}
            PREMIUM_ENCRYPTION_KEY=${{ secrets.PREMIUM_ENCRYPTION_KEY }}
            OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}
            WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET }}
            VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}
            VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}
            VITE_STRIPE_PUBLISHABLE_KEY=${{ secrets.VITE_STRIPE_PUBLISHABLE_KEY }}
            VITE_STRIPE_PREMIUM_PRICE_ID=${{ secrets.VITE_STRIPE_PREMIUM_PRICE_ID }}
            VITE_BASIC_ENCRYPTION_KEY=${{ secrets.BASIC_ENCRYPTION_KEY }}
            VITE_PREMIUM_ENCRYPTION_KEY=${{ secrets.PREMIUM_ENCRYPTION_KEY }}
            VITE_WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET }}
          secret-files: |
            "env_file=.env.production"

      # Build and push nginx image
      - name: Build and push nginx Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: nginx
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-nginx.outputs.tags }}
          labels: ${{ steps.meta-nginx.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GIT_COMMIT_HASH=${{ github.sha }}
            VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}
            VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}
            VITE_STRIPE_PUBLISHABLE_KEY=${{ secrets.VITE_STRIPE_PUBLISHABLE_KEY }}
            VITE_STRIPE_PREMIUM_PRICE_ID=${{ secrets.VITE_STRIPE_PREMIUM_PRICE_ID }}
            VITE_BASIC_ENCRYPTION_KEY=${{ secrets.BASIC_ENCRYPTION_KEY }}
            VITE_PREMIUM_ENCRYPTION_KEY=${{ secrets.PREMIUM_ENCRYPTION_KEY }}
            VITE_WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET }}
          secret-files: |
            "env_file=.env.production"

      # Trigger deployment if on main branch
#      - name: Trigger deployment
#        if: github.ref == 'refs/heads/main'
#        run: |
#          echo "Deployment triggered for version ${{ steps.meta.outputs.version }}"
          # Add deployment script or webhook here 