name:  Build and Push Multi-Platform Docker Image
on:
 push:
   branches:
     - "main"

permissions:
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push by platform
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/ireccode/sap-exam-prep:latest
            ghcr.io/ireccode/sap-exam-prep:${{ github.sha }}
          build-args: |
            $(cat .env | sed 's/^/--build-arg /')
